### ISSUE TITLE
Chuyển sang functional programming

### ISSUE THREAD

**Issue by oTranThanhNghia** [tiendoanimpl/MoneyManager#1]
+ Chuyển hết class component sang function component
+ Học cách sử dụng React Hook nhé 
https://reactjs.org/docs/hooks-intro.html

Ngoài ra em lên ý tưởng trước khi làm nhé. Kiểu như phải có specs trước khi code ý :)

**Comment by oTranThanhNghia** [comment]
Chưa thấy update gì nhỉ :)

**Comment by tiendoanimpl** [comment]
em update sang function component rồi đó ạ
